import Head from "next/head";
import React from "react";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Denise Bamberg</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Welcome to my portfolio!</h1>
            <p>This is where you can learn more about my work and projects.</p>
        </div>
    );
}
